name: Cypress Tests

on:
    workflow_dispatch:

    push:
        branches: [master]

    pull_request:
        branches: [master]

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        name: E2E on Chrome

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  browser: chrome
                  record: true
                  parallel: true
              env:
                  group: 'UI-Chrome'
                  TZ: Europe/Warsaw
                  CYPRESS_ENV: Poland
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Screenshots report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots
                  if-no-files-found: ignore

            - name: Video report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: cypress-videos
                  path: cypress/videos
                  if-no-files-found: ignore

            - name: Create cucumber-report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: cucumber-report
                  path: ./
                  retention-days: 15

    deploy:
        needs: test
        if: always()
        runs-on: ubuntu-latest
        steps:
            - name: Download cucumber report artifact
              if: always()
              uses: actions/download-artifact@v4

            - name: Display structure of downloaded files
              run: ls -R

            - name: Deploy report to Github Pages
              uses: peaceiris/actions-gh-pages@v2
              env:
                  PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: ./
